version: '2'

services:
  db:
    image: datajoint/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: simple
            MYSQL_ROOT_PASSWORD: simple
    ports:
            - "80:80"
    links:
            # for mysql container
            - "db:db"
  web:
    image: php:7.2-apache
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "8082:80"
    links:
      - db
    volumes:
      - ./app:/var/www/html/